[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clipsync"
version = "0.1.0"
description = "Cross‑device clipboard sync"
requires-python = ">=3.7"
dependencies = [
  "pyperclip>=1.8",
  "tabulate>=0.9",
  "click>=8.2"
]

[project.scripts]
clipsync = "cli:cli"